import Head from 'next/head'
import Navbar from "../components/navbar";
import styled from "@emotion/styled";
import {Box, Container} from "@mui/material";
import * as React from "react";
import Showcase from "../components/showcase";


export default function Home() {
  return (
    <>
      <Head>
        <title>Flex Hosting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
          <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet" />
      </Head>
      <Box sx={{backgroundColor:'#047aed'}}>
        <Navbar />
        <Showcase />
        https://awesome-dijkstra-8b92c7.netlify.app/index.html
        https://dev.to/hajhosein/nextjs-mui-v5-tutorial-2k35
      </Box>

    </>
  )
}
